### ISSUE TITLE
gitlab 使用这个后 会有一个小问题

### ISSUE THREAD

**Issue by Bravoyk** [renny-ren/omniauth-feishu#2]
每次用飞书登录的人都是第一个使用飞书登录的人、、。

**Comment by renny-ren** [comment]
看一下你 `User.from_omniauth` 的逻辑
另外看看是不是 session 没有清？

**Comment by Tom2049** [comment]
同样的情况, 我也尝试使用飞书登录 Gitlab.

是在 Gitlab 的回调控制器中清空这个 session 吗?   对  Ruby 不太了解.

**Comment by renny-ren** [comment]
对，检查下回调控制器里面的逻辑
